create extension if not exists pgcrypto;

create table if not exists projects (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null, description text, github_repo text, vercel_project_id text, vercel_url text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists chats (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, title text not null default 'New chat', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists messages (id uuid primary key default gen_random_uuid(), chat_id uuid not null references chats(id) on delete cascade, role text not null check(role in ('user','assistant','system')), content text not null, created_at timestamptz not null default now());
create table if not exists project_files (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, path text not null, content text not null default '', version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,path));
create table if not exists memories (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, type text not null, content text not null, created_at timestamptz not null default now());
create table if not exists provider_keys (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, provider text not null, encrypted_key text not null, label text, enabled boolean not null default true, priority integer not null default 100, cooldown_until timestamptz, created_at timestamptz not null default now());
create table if not exists github_connections (id uuid primary key default gen_random_uuid(), owner_id uuid unique not null references auth.users(id) on delete cascade, github_user_id text not null, login text not null, encrypted_token text not null, scopes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists agent_runs (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, request text not null, status text not null check(status in ('running','completed','failed')), summary text, max_iterations integer not null default 3, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists agent_actions (id uuid primary key default gen_random_uuid(), run_id uuid not null references agent_runs(id) on delete cascade, iteration integer not null, action_type text not null, path text, before_content text, after_content text, created_at timestamptz not null default now());
create table if not exists rate_limits (owner_id uuid not null references auth.users(id) on delete cascade, bucket text not null, window_started_at timestamptz not null, count integer not null default 0, primary key(owner_id,bucket));

alter table projects add column if not exists vercel_project_id text;
alter table projects add column if not exists vercel_url text;

alter table projects enable row level security; alter table chats enable row level security; alter table messages enable row level security; alter table project_files enable row level security; alter table memories enable row level security; alter table provider_keys enable row level security; alter table github_connections enable row level security; alter table agent_runs enable row level security; alter table agent_actions enable row level security; alter table rate_limits enable row level security;

drop policy if exists "project owner" on projects; create policy "project owner" on projects for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
drop policy if exists "chat through project" on chats; create policy "chat through project" on chats for all using(exists(select 1 from projects p where p.id=chats.project_id and p.owner_id=auth.uid())) with check(exists(select 1 from projects p where p.id=chats.project_id and p.owner_id=auth.uid()));
drop policy if exists "message through chat" on messages; create policy "message through chat" on messages for all using(exists(select 1 from chats c join projects p on p.id=c.project_id where c.id=messages.chat_id and p.owner_id=auth.uid())) with check(exists(select 1 from chats c join projects p on p.id=c.project_id where c.id=messages.chat_id and p.owner_id=auth.uid()));
drop policy if exists "file through project" on project_files; create policy "file through project" on project_files for all using(exists(select 1 from projects p where p.id=project_files.project_id and p.owner_id=auth.uid())) with check(exists(select 1 from projects p where p.id=project_files.project_id and p.owner_id=auth.uid()));
drop policy if exists "memory through project" on memories; create policy "memory through project" on memories for all using(exists(select 1 from projects p where p.id=memories.project_id and p.owner_id=auth.uid())) with check(exists(select 1 from projects p where p.id=memories.project_id and p.owner_id=auth.uid()));
drop policy if exists "provider key owner" on provider_keys; create policy "provider key owner" on provider_keys for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
drop policy if exists "github connection owner" on github_connections; create policy "github connection owner" on github_connections for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
drop policy if exists "agent run through project" on agent_runs; create policy "agent run through project" on agent_runs for all using(exists(select 1 from projects p where p.id=agent_runs.project_id and p.owner_id=auth.uid())) with check(exists(select 1 from projects p where p.id=agent_runs.project_id and p.owner_id=auth.uid()));
drop policy if exists "agent actions through run" on agent_actions; create policy "agent actions through run" on agent_actions for all using(exists(select 1 from agent_runs r join projects p on p.id=r.project_id where r.id=agent_actions.run_id and p.owner_id=auth.uid())) with check(exists(select 1 from agent_runs r join projects p on p.id=r.project_id where r.id=agent_actions.run_id and p.owner_id=auth.uid()));

drop policy if exists "rate limit owner" on rate_limits; create policy "rate limit owner" on rate_limits for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);

create or replace function consume_rate_limit(p_bucket text,p_limit integer,p_window_seconds integer) returns boolean language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); now_ts timestamptz:=now(); current_count integer; begin if uid is null then return false; end if; insert into rate_limits(owner_id,bucket,window_started_at,count) values(uid,p_bucket,now_ts,1) on conflict(owner_id,bucket) do update set count=case when rate_limits.window_started_at + make_interval(secs=>p_window_seconds) <= now_ts then 1 else rate_limits.count+1 end, window_started_at=case when rate_limits.window_started_at + make_interval(secs=>p_window_seconds) <= now_ts then now_ts else rate_limits.window_started_at end returning count into current_count; return current_count <= p_limit; end; $$;
revoke all on function consume_rate_limit(text,integer,integer) from public; grant execute on function consume_rate_limit(text,integer,integer) to authenticated;

create index if not exists provider_keys_owner_priority_idx on provider_keys(owner_id,enabled,priority); create index if not exists project_files_project_path_idx on project_files(project_id,path); create index if not exists messages_chat_created_idx on messages(chat_id,created_at); create index if not exists memories_project_created_idx on memories(project_id,created_at desc); create index if not exists agent_actions_run_iteration_idx on agent_actions(run_id,iteration,created_at); create index if not exists agent_runs_project_created_idx on agent_runs(project_id,created_at desc);
