'use client';

import { useState } from 'react';
import { AlertTriangle, BarChart3, Check, Globe2, Loader2, Save, Trash2 } from 'lucide-react';
import { deleteProject, setProjectPublic, updateProject } from '@/app/actions/projects';

export function ProjectSettingsClient({ project, plan, usage, limits, projectCount }: { project: { id: string; name: string; is_public: boolean }; plan: 'FREE' | 'PRO'; usage: { message_count: number; proposal_count: number }; limits: { projects: number; messagesPerDay: number; proposalsPerDay: number }; projectCount: number }) {
  const [name, setName] = useState(project.name);
  const [isPublic, setIsPublic] = useState(project.is_public);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState('');
  const [deleting, setDeleting] = useState(false);
  const unlimited = (value: number) => Number.isFinite(value) ? String(value) : 'Unlimited';
  async function saveName() { setSaving(true); setNotice(''); try { await updateProject(project.id, name); setNotice('Project name saved.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Could not save.'); } finally { setSaving(false); } }
  async function togglePublic() { setSaving(true); setNotice(''); try { const next = !isPublic; await setProjectPublic(project.id, next); setIsPublic(next); setNotice(next ? 'Project is now public.' : 'Project is private.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Could not update sharing.'); } finally { setSaving(false); } }
  return <div className="space-y-4"><section className="rounded-3xl border border-zinc-800 bg-[#10131f] p-4"><div className="mb-4 flex items-center gap-2"><Save size={17} className="text-violet-400"/><h2 className="font-semibold">Project</h2></div><label className="block text-xs text-zinc-500">Project name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} className="mt-2 h-11 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-3 text-sm text-zinc-100 outline-none focus:border-violet-500"/></label><button onClick={saveName} disabled={saving || !name.trim()} className="mt-3 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-violet-600 text-sm font-semibold disabled:opacity-50">{saving?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>}Save name</button>{notice&&<p className="mt-2 text-xs text-zinc-500">{notice}</p>}</section>
    <section className="rounded-3xl border border-zinc-800 bg-[#10131f] p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-300"><Globe2 size={19}/></div><div className="flex-1"><h2 className="font-semibold">Public sharing</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Anyone with the share link can view your files and live preview. They cannot edit the project.</p></div><button onClick={togglePublic} disabled={saving} className={`relative h-7 w-12 rounded-full transition ${isPublic?'bg-violet-600':'bg-zinc-800'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${isPublic?'left-6':'left-1'}`}/></button></div>{isPublic&&<div className="mt-3 rounded-xl border border-emerald-500/15 bg-emerald-500/5 px-3 py-2 text-xs text-emerald-300 break-all">/share/{project.id}</div>}</section>
    <section className="rounded-3xl border border-zinc-800 bg-[#10131f] p-4"><div className="mb-4 flex items-center gap-2"><BarChart3 size={17} className="text-indigo-300"/><h2 className="font-semibold">Usage</h2><span className="ml-auto rounded-full bg-violet-500/10 px-2 py-1 text-[10px] text-violet-300">{plan}</span></div><div className="grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl bg-zinc-950 p-3"><div className="text-zinc-600">Messages today</div><div className="mt-1 text-lg font-semibold">{usage.message_count} <span className="text-xs text-zinc-600">/ {unlimited(limits.messagesPerDay)}</span></div></div><div className="rounded-2xl bg-zinc-950 p-3"><div className="text-zinc-600">Proposals today</div><div className="mt-1 text-lg font-semibold">{usage.proposal_count} <span className="text-xs text-zinc-600">/ {unlimited(limits.proposalsPerDay)}</span></div></div><div className="col-span-2 rounded-2xl bg-zinc-950 p-3"><div className="text-zinc-600">Projects</div><div className="mt-1 text-lg font-semibold">{projectCount} <span className="text-xs text-zinc-600">/ {unlimited(limits.projects)}</span></div></div></div></section>
    <section className="rounded-3xl border border-red-500/15 bg-red-500/[0.03] p-4"><div className="flex items-start gap-3"><AlertTriangle size={18} className="mt-0.5 text-red-300"/><div className="flex-1"><h2 className="font-semibold text-red-200">Danger zone</h2><p className="mt-1 text-xs leading-5 text-zinc-600">Delete this project and all generated files, proposals, and messages.</p></div></div><button onClick={async()=>{if(!confirm('Delete this project permanently?'))return;setDeleting(true);await deleteProject(project.id);}} disabled={deleting} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-red-500/30 text-sm text-red-300 disabled:opacity-50">{deleting?<Loader2 size={16} className="animate-spin"/>:<Trash2 size={16}/>}Delete project</button></section></div>;
}
