'use client';
import { useEffect, useState } from 'react';

type Repo={full_name:string;name:string;default_branch:string;private:boolean};
export function IntegrationsPanel({projectId,onNotice}:{projectId?:string;onNotice:(s:string)=>void}){
 const [connected,setConnected]=useState(false),[login,setLogin]=useState(''),[repos,setRepos]=useState<Repo[]>([]),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[deploying,setDeploying]=useState(false),[vercel,setVercel]=useState(false);
 async function load(){const r=await fetch('/api/github/repos');if(r.ok){const d=await r.json();setConnected(!!d.connected);setLogin(d.login||'');setRepos(d.repositories||[]);if(!repo&&d.repositories?.[0]){setRepo(d.repositories[0].full_name);setBranch(d.repositories[0].default_branch||'main')}} const v=await fetch('/api/vercel/projects');if(v.ok)setVercel(!!(await v.json()).configured)}
 useEffect(()=>{load()},[]);
 async function publish(){if(!projectId||!repo)return;const r=await fetch('/api/github/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,repo,branch,message:'Update from Nexa Code AI'})});const d=await r.json();onNotice(r.ok?`Published ${d.result.files} file(s) to ${d.result.repository}. Commit ${d.result.commit.slice(0,7)}.`:d.error||'GitHub publish failed.');}
 async function deploy(){if(!projectId)return;setDeploying(true);const r=await fetch('/api/vercel/deploy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId})});const d=await r.json();setDeploying(false);onNotice(r.ok?`Vercel deployment created${d.deployment?.url?`: ${d.deployment.url}`:''}.`:d.error||'Vercel deployment failed.');}
 return <div className="integration-panel">
  {!connected?<button className="primary full" onClick={()=>location.href='/api/github/connect'}>Connect GitHub</button>:<><div className="muted">GitHub connected as <strong>{login}</strong></div><select value={repo} onChange={e=>{setRepo(e.target.value);const r=repos.find(x=>x.full_name===e.target.value);setBranch(r?.default_branch||'main')}}>{repos.map(r=><option key={r.full_name} value={r.full_name}>{r.full_name}{r.private?' · private':''}</option>)}</select><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="Branch"/><div className="integration-actions"><button onClick={publish} disabled={!projectId||!repo}>Push to GitHub</button><button onClick={()=>{location.href='/api/github/connect'}}>Reconnect</button></div><button className="primary full" onClick={deploy} disabled={!projectId||deploying||!vercel}>{deploying?'Deploying…':'Deploy to Vercel'}</button>{!vercel&&<div className="muted">Set VERCEL_TOKEN on the server to enable deployments.</div>}<button className="danger full" onClick={async()=>{await fetch('/api/github/disconnect',{method:'POST'});setConnected(false);setRepos([]);onNotice('GitHub disconnected.')}}>Disconnect GitHub</button></>}
 </div>
}
